### ISSUE TITLE
pandas 0.18.0 incompatibility in tests

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#130]
The pvlib tests pass using the new pandas 0.18.0, with one exception: ``test_calcparams_desoto``. The data is still being calculated correctly, but the np.round function used in the test now chokes on the Series object. The helpful pydata people are going to fix this upstream for pandas 0.18.1, but I'll hack around this in the meantime. For more, see pydata/pandas#12600. 

```
======================================================================
ERROR: pvlib.test.test_pvsystem.test_calcparams_desoto
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/holmgren/miniconda3/envs/pvlib35/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/holmgren/git_repos/pvlib-python/pvlib/test/test_pvsystem.py", line 206, in test_calcparams_desoto
    assert_series_equal(np.round(IL, 3), pd.Series([0.0, 6.036], index=times))
  File "/Users/holmgren/miniconda3/envs/pvlib35/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 2786, in round_
    return round(decimals, out)
TypeError: round() takes from 1 to 2 positional arguments but 3 were given

======================================================================
ERROR: pvlib.test.test_pvsystem.test_PVSystem_calcparams_desoto
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/holmgren/miniconda3/envs/pvlib35/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/holmgren/git_repos/pvlib-python/pvlib/test/test_pvsystem.py", line 226, in test_PVSystem_calcparams_desoto
    assert_series_equal(np.round(IL, 3), pd.Series([0.0, 6.036], index=times))
  File "/Users/holmgren/miniconda3/envs/pvlib35/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 2786, in round_
    return round(decimals, out)
TypeError: round() takes from 1 to 2 positional arguments but 3 were given

----------------------------------------------------------------------
Ran 232 tests in 72.728s

FAILED (SKIP=2, errors=2)
```

**Comment by wholmgren** [comment]
Also, this why my recent PRs #128 #129 are failing.
