### ISSUE TITLE
ModuleNotFoundError: No module named 'pvfactors'

### ISSUE THREAD

**Issue by avarf** [pvlib/pvlib-python#1513]
Hi, I am trying to run the [Bifacial Modeling Example](https://pvlib-python.readthedocs.io/en/stable/gallery/bifacial/plot_bifi_model_mc.html#sphx-glr-gallery-bifacial-plot-bifi-model-mc-py) on my machine but I get below error:
```bash
$ python pv.py 
Traceback (most recent call last):
  File "pv.py", line 99, in <module>
    index_observed_pvrow=1
  File "/home/avarf/.local/lib/python3.6/site-packages/pvlib/bifacial/pvfactors.py", line 95, in pvfactors_timeseries
    from pvfactors.run import run_timeseries_engine
ModuleNotFoundError: No module named 'pvfactors'
``` 

**To Reproduce**
1. Install the pvlib
2. Download/copy the example to a .py file
3. Run the file using `python`

**Versions:**
 - OS: Ubuntu 18.04
 - ``pvlib.__version__``: 0.9.1
 - ``pandas.__version__``: 1.1.5
 - python: 3.6.9

**Additional context**
I thought it might be related to the https://github.com/pvlib/pvlib-python/issues/699 but I am able to import `pvfactors_timeseries` but it is not able to import the `run_timeseries_engine`:
```bash
>>> from pvlib.bifacial.pvfactors import pvfactors_timeseries
>>> 
>>> pvfactors_timeseries
<function pvfactors_timeseries at 0x7f0dae0680d0>
>>> 
>>> 
>>> from pvfactors.run import run_timeseries_engine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pvfactors'
>>> 
>>> 
>>> from pvlib.bifacial import pvfactors
>>> from pvfactors.run import run_timeseries_engine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pvfactors'
>>> 
>>> 
>>> from pvfactors import run
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pvfactors'
```

**Comment by kanderso-nrel** [comment]
Hi, `pvfactors` is currently an [optional](https://github.com/pvlib/pvlib-python/blob/master/setup.py#L41-L61) dependency, so it's not installed automatically when you `pip install pvlib`.  So just install it in the same environment where you have pvlib: `pip install pvfactors`.  Or you can install all the optional dependencies with `pip install pvlib[optional]`, but that's overkill just for this situation.

Maybe we should add a note to that effect at the top of any gallery example using an optional dependency.

**Comment by avarf** [comment]
Hi @kanderso-nrel , thank you that solved that problem but now I am getting below error:
```bash
$ python pv-bifacial.py 
/home/avarf/.local/lib/python3.6/site-packages/pvlib/singlediode.py:520: RuntimeWarning: invalid value encountered in greater
  idx_p = 0. < Gsh
/home/avarf/.local/lib/python3.6/site-packages/pvlib/tools.py:350: RuntimeWarning: invalid value encountered in greater
  df['SW_Flag'] = df['f1'] > df['f2']

```

**Comment by kanderso-nrel** [comment]
This is just a warning (not an error), perhaps due to nighttime values or similar.  If you do not see an issue in the results then it is likely safe to ignore it.

**Comment by avarf** [comment]
Since the program is not producing any plot I just added a print command at the end and this is the output (note many NaN columns):
```bash
$ python pv-bifacial.py
/home/avarf/.local/lib/python3.6/site-packages/pvlib/singlediode.py:520: RuntimeWarning: invalid value encountered in greater
  idx_p = 0. < Gsh
/home/avarf/.local/lib/python3.6/site-packages/pvlib/tools.py:350: RuntimeWarning: invalid value encountered in greater
  df['SW_Flag'] = df['f1'] > df['f2']
ModelChainResult(_singleton_tuples=False, solar_position=None, airmass=None, ac=2021-06-21 00:00:00-05:00   -0.075
2021-06-21 00:01:00-05:00   -0.075
2021-06-21 00:02:00-05:00   -0.075
2021-06-21 00:03:00-05:00   -0.075
2021-06-21 00:04:00-05:00   -0.075
                             ...  
2021-06-21 23:56:00-05:00   -0.075
2021-06-21 23:57:00-05:00   -0.075
2021-06-21 23:58:00-05:00   -0.075
2021-06-21 23:59:00-05:00   -0.075
2021-06-22 00:00:00-05:00   -0.075
Freq: T, Length: 1441, dtype: float64, tracking=None, losses=1, total_irrad=Empty DataFrame
Columns: []
Index: [2021-06-21 00:00:00-05:00, 2021-06-21 00:01:00-05:00, 2021-06-21 00:02:00-05:00, 2021-06-21 00:03:00-05:00, 2021-06-21 00:04:00-05:00, 2021-06-21 00:05:00-05:00, 2021-06-21 00:06:00-05:00, 2021-06-21 00:07:00-05:00, 2021-06-21 00:08:00-05:00, 2021-06-21 00:09:00-05:00, 2021-06-21 00:10:00-05:00, 2021-06-21 00:11:00-05:00, 2021-06-21 00:12:00-05:00, 2021-06-21 00:13:00-05:00, 2021-06-21 00:14:00-05:00, 2021-06-21 00:15:00-05:00, 2021-06-21 00:16:00-05:00, 2021-06-21 00:17:00-05:00, 2021-06-21 00:18:00-05:00, 2021-06-21 00:19:00-05:00, 2021-06-21 00:20:00-05:00, 2021-06-21 00:21:00-05:00, 2021-06-21 00:22:00-05:00, 2021-06-21 00:23:00-05:00, 2021-06-21 00:24:00-05:00, 2021-06-21 00:25:00-05:00, 2021-06-21 00:26:00-05:00, 2021-06-21 00:27:00-05:00, 2021-06-21 00:28:00-05:00, 2021-06-21 00:29:00-05:00, 2021-06-21 00:30:00-05:00, 2021-06-21 00:31:00-05:00, 2021-06-21 00:32:00-05:00, 2021-06-21 00:33:00-05:00, 2021-06-21 00:34:00-05:00, 2021-06-21 00:35:00-05:00, 2021-06-21 00:36:00-05:00, 2021-06-21 00:37:00-05:00, 2021-06-21 00:38:00-05:00, 2021-06-21 00:39:00-05:00, 2021-06-21 00:40:00-05:00, 2021-06-21 00:41:00-05:00, 2021-06-21 00:42:00-05:00, 2021-06-21 00:43:00-05:00, 2021-06-21 00:44:00-05:00, 2021-06-21 00:45:00-05:00, 2021-06-21 00:46:00-05:00, 2021-06-21 00:47:00-05:00, 2021-06-21 00:48:00-05:00, 2021-06-21 00:49:00-05:00, 2021-06-21 00:50:00-05:00, 2021-06-21 00:51:00-05:00, 2021-06-21 00:52:00-05:00, 2021-06-21 00:53:00-05:00, 2021-06-21 00:54:00-05:00, 2021-06-21 00:55:00-05:00, 2021-06-21 00:56:00-05:00, 2021-06-21 00:57:00-05:00, 2021-06-21 00:58:00-05:00, 2021-06-21 00:59:00-05:00, 2021-06-21 01:00:00-05:00, 2021-06-21 01:01:00-05:00, 2021-06-21 01:02:00-05:00, 2021-06-21 01:03:00-05:00, 2021-06-21 01:04:00-05:00, 2021-06-21 01:05:00-05:00, 2021-06-21 01:06:00-05:00, 2021-06-21 01:07:00-05:00, 2021-06-21 01:08:00-05:00, 2021-06-21 01:09:00-05:00, 2021-06-21 01:10:00-05:00, 2021-06-21 01:11:00-05:00, 2021-06-21 01:12:00-05:00, 2021-06-21 01:13:00-05:00, 2021-06-21 01:14:00-05:00, 2021-06-21 01:15:00-05:00, 2021-06-21 01:16:00-05:00, 2021-06-21 01:17:00-05:00, 2021-06-21 01:18:00-05:00, 2021-06-21 01:19:00-05:00, 2021-06-21 01:20:00-05:00, 2021-06-21 01:21:00-05:00, 2021-06-21 01:22:00-05:00, 2021-06-21 01:23:00-05:00, 2021-06-21 01:24:00-05:00, 2021-06-21 01:25:00-05:00, 2021-06-21 01:26:00-05:00, 2021-06-21 01:27:00-05:00, 2021-06-21 01:28:00-05:00, 2021-06-21 01:29:00-05:00, 2021-06-21 01:30:00-05:00, 2021-06-21 01:31:00-05:00, 2021-06-21 01:32:00-05:00, 2021-06-21 01:33:00-05:00, 2021-06-21 01:34:00-05:00, 2021-06-21 01:35:00-05:00, 2021-06-21 01:36:00-05:00, 2021-06-21 01:37:00-05:00, 2021-06-21 01:38:00-05:00, 2021-06-21 01:39:00-05:00, ...]

[1441 rows x 0 columns], aoi=None, aoi_modifier=None, spectral_modifier=None, cell_temperature=2021-06-21 00:00:00-05:00   NaN
2021-06-21 00:01:00-05:00   NaN
2021-06-21 00:02:00-05:00   NaN
2021-06-21 00:03:00-05:00   NaN
2021-06-21 00:04:00-05:00   NaN
                             ..
2021-06-21 23:56:00-05:00   NaN
2021-06-21 23:57:00-05:00   NaN
2021-06-21 23:58:00-05:00   NaN
2021-06-21 23:59:00-05:00   NaN
2021-06-22 00:00:00-05:00   NaN
Freq: T, Length: 1441, dtype: float64, effective_irradiance=2021-06-21 00:00:00-05:00   NaN
2021-06-21 00:01:00-05:00   NaN
2021-06-21 00:02:00-05:00   NaN
2021-06-21 00:03:00-05:00   NaN
2021-06-21 00:04:00-05:00   NaN
                             ..
2021-06-21 23:56:00-05:00   NaN
2021-06-21 23:57:00-05:00   NaN
2021-06-21 23:58:00-05:00   NaN
2021-06-21 23:59:00-05:00   NaN
2021-06-22 00:00:00-05:00   NaN
Freq: T, Name: effective_irradiance, Length: 1441, dtype: float64, dc=                           i_sc  v_oc  i_mp  v_mp  p_mp  i_x  i_xx
2021-06-21 00:00:00-05:00   0.0   0.0   0.0   0.0   0.0  0.0   0.0
2021-06-21 00:01:00-05:00   0.0   0.0   0.0   0.0   0.0  0.0   0.0
2021-06-21 00:02:00-05:00   0.0   0.0   0.0   0.0   0.0  0.0   0.0
2021-06-21 00:03:00-05:00   0.0   0.0   0.0   0.0   0.0  0.0   0.0
2021-06-21 00:04:00-05:00   0.0   0.0   0.0   0.0   0.0  0.0   0.0
...                         ...   ...   ...   ...   ...  ...   ...
2021-06-21 23:56:00-05:00   0.0   0.0   0.0   0.0   0.0  0.0   0.0
2021-06-21 23:57:00-05:00   0.0   0.0   0.0   0.0   0.0  0.0   0.0
2021-06-21 23:58:00-05:00   0.0   0.0   0.0   0.0   0.0  0.0   0.0
2021-06-21 23:59:00-05:00   0.0   0.0   0.0   0.0   0.0  0.0   0.0
2021-06-22 00:00:00-05:00   0.0   0.0   0.0   0.0   0.0  0.0   0.0

[1441 rows x 7 columns], diode_params=                           I_L  I_o       R_s  R_sh  nNsVth
2021-06-21 00:00:00-05:00  NaN  NaN  0.251086   NaN     NaN
2021-06-21 00:01:00-05:00  NaN  NaN  0.251086   NaN     NaN
2021-06-21 00:02:00-05:00  NaN  NaN  0.251086   NaN     NaN
2021-06-21 00:03:00-05:00  NaN  NaN  0.251086   NaN     NaN
2021-06-21 00:04:00-05:00  NaN  NaN  0.251086   NaN     NaN
...                        ...  ...       ...   ...     ...
2021-06-21 23:56:00-05:00  NaN  NaN  0.251086   NaN     NaN
2021-06-21 23:57:00-05:00  NaN  NaN  0.251086   NaN     NaN
2021-06-21 23:58:00-05:00  NaN  NaN  0.251086   NaN     NaN
2021-06-21 23:59:00-05:00  NaN  NaN  0.251086   NaN     NaN
2021-06-22 00:00:00-05:00  NaN  NaN  0.251086   NaN     NaN

[1441 rows x 5 columns], dc_ohmic_losses=None, weather=                           wind_speed  temp_air
2021-06-21 00:00:00-05:00           0        20
2021-06-21 00:01:00-05:00           0        20
2021-06-21 00:02:00-05:00           0        20
2021-06-21 00:03:00-05:00           0        20
2021-06-21 00:04:00-05:00           0        20
...                               ...       ...
2021-06-21 23:56:00-05:00           0        20
2021-06-21 23:57:00-05:00           0        20
2021-06-21 23:58:00-05:00           0        20
2021-06-21 23:59:00-05:00           0        20
2021-06-22 00:00:00-05:00           0        20

[1441 rows x 2 columns], times=DatetimeIndex(['2021-06-21 00:00:00-05:00', '2021-06-21 00:01:00-05:00',
               '2021-06-21 00:02:00-05:00', '2021-06-21 00:03:00-05:00',
               '2021-06-21 00:04:00-05:00', '2021-06-21 00:05:00-05:00',
               '2021-06-21 00:06:00-05:00', '2021-06-21 00:07:00-05:00',
               '2021-06-21 00:08:00-05:00', '2021-06-21 00:09:00-05:00',
               ...
               '2021-06-21 23:51:00-05:00', '2021-06-21 23:52:00-05:00',
               '2021-06-21 23:53:00-05:00', '2021-06-21 23:54:00-05:00',
               '2021-06-21 23:55:00-05:00', '2021-06-21 23:56:00-05:00',
               '2021-06-21 23:57:00-05:00', '2021-06-21 23:58:00-05:00',
               '2021-06-21 23:59:00-05:00', '2021-06-22 00:00:00-05:00'],
              dtype='datetime64[ns, Etc/GMT+5]', length=1441, freq='T'))
```
This is the code:
```python
mc_bifi = modelchain.ModelChain(system, site_location, aoi_model='no_loss')
mc_bifi.run_model_from_effective_irradiance(irrad)

print(mc_bifi.results)

# plot results
mc_bifi.results.ac.plot(title='Bifacial Simulation on June Solstice',
                        ylabel='AC Power')
```

**Comment by kanderso-nrel** [comment]
It is only printing a few values at the beginning and end of the data, which are all at night, so maybe there are real values during daytime hours that are just not being shown in that print out.  You can also check things like `mc_bifi.results.ac.sum()` which will be the total summed 1-minute power (divide by 60 to get energy in Watt-hours).

FYI If you are running from the command line (not inside an IDE or similar), you may need to add `plt.show()` at the end of the script to make your plots appear.

**Comment by avarf** [comment]
Thank you for your help, with sum I can see the sum of the output ac (whihc is not zero) and I also edited the code a little and after using matplotlib now I can see the plot too:
```python
print(mc_bifi.results.ac.sum())

# plot results
# mc_bifi.results.ac.plot(title='Bifacial Simulation on June Solstice',
#                         ylabel='AC Power')
import matplotlib.pyplot as plt

plt.figure()
plt.title('Bifacial vs Monofacial Simulation - June Solstice')
mc_bifi.results.ac.plot(title='Bifacial Simulation on June Solstice', ylabel='AC Power')
plt.legend()
plt.show()
```

FYI, I was running the code both in the VSCode and terminal but the plot was missing in both cases.

I will close this issue and the issue related to plot (https://github.com/pvlib/pvlib-python/issues/1514).
