### ISSUE TITLE
Key Error.  pvlib.pvsystem.sapm_effective_irradiance

### ISSUE THREAD

**Issue by apct69** [pvlib/pvlib-python#2025]
Hi! After being able to choose my panels after my last issue, I started following the intro tutorial again. 
(My objective is to first get an annual simulation for the yield before further investigation)

When getting the effective irradiance with the code below, I get a bunch of errors where I don't know where to start. 
Do I get these errors because I didn't use the Sandia module database and the values are not organized the same with CEC? 

Thanks a lot! 
AP

```
 effective_irradiance = pvlib.pvsystem.sapm_effective_irradiance(
        total_irradiance['poa_direct'],
        total_irradiance['poa_diffuse'],
        am_abs,
        aoi,
        module,
    )
```
Traceback (most recent call last):
  File "C:\Users\AP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\indexes\base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 153, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 182, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'A4'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\AP\Dropbox\USMB\S8\RP\pvlib_test.py", line 80, in <module>
    effective_irradiance = pvlib.pvsystem.sapm_effective_irradiance(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pvlib\pvsystem.py", line 2335, in sapm_effective_irradiance
    F1 = spectrum.spectral_factor_sapm(airmass_absolute, module)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pvlib\spectrum\mismatch.py", line 440, in spectral_factor_sapm
    am_coeff = [module['A4'], module['A3'], module['A2'], module['A1'],
                ~~~~~~^^^^^^
  File "C:\Users\AP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\series.py", line 1111, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\series.py", line 1227, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\indexes\base.py", line 3809, in get_loc
    raise KeyError(key) from err
KeyError: 'A4'

**Comment by cwhanse** [comment]
Hi @apct69 apct69, this question is about using pvlib, rather than reporting a bug or requesting a new feature. Can you repost the question to the pvlib google group https://groups.google.com/g/pvlib-python or at stackoverflow (tag pvlib)?

The CEC module database doesn't include spectral model parameters. Parameters 'A4', ..., 'A0' are for the SAPM spectral adjustment factor. You can look through the SAPM database and find parameters for a module similar to the one you are interested in (the most important feature is the type of the cell), or set effective irradiance equal to plane-of-array irradiance which ignores spectrum effect on photocurrent.
