### ISSUE TITLE
ValueError: Cannot cast DatetimeIndex to dtype int32

### ISSUE THREAD

**Issue by SheffieldSolar** [pvlib/pvlib-python#63]
In windows, receive an error using index.astype in solarposition.py line 284:
> \>\>\> from datetime import datetime
\>\>\> t = datetime(2014,1,1,12,0,0)
\>\>\> import pandas as pd
\>\>\> panda_t = pd.to_datetime([t,])
\>\>\> import pvlib
\>\>\> loc = pvlib.location.Location(53, -1.5, tz='UTC')
\>\>\> print pvlib.solarposition.get_solarposition(panda_t, loc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ph1jt\Anaconda\lib\site-packages\pvlib\solarposition.py", line 79, in get_solarposition
    how='numpy', \*\*kwargs)
  File "C:\Users\ph1jt\Anaconda\lib\site-packages\pvlib\solarposition.py", line 284, in spa_python
    unixtime = localize_to_utc(time, location).astype(int)/10\*\*9
  File "C:\Users\ph1jt\Anaconda\lib\site-packages\pandas\tseries\index.py", line 713, in astype
    raise ValueError('Cannot cast DatetimeIndex to dtype %s' % dtype)
ValueError: Cannot cast DatetimeIndex to dtype int32

Changing line 284 in solarposition from:
```python
    unixtime = localize_to_utc(time, location).astype(int)/10**9
```
to:
```python
    unixtime = localize_to_utc(time, location).astype('int64')/10**9
```
fixes the issue.

**Comment by wholmgren** [comment]
Thanks @SheffieldSolar and @alorenzo175
