### ISSUE TITLE
requests package requirement not listed

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#725]
**Describe the bug**
`import pvlib` fails due to unspecified `requests` dependency:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/holmgren/miniconda3/envs/pvlibtest/lib/python3.7/site-packages/pvlib/__init__.py", line 9, in <module>
    from pvlib import iotools
  File "/Users/holmgren/miniconda3/envs/pvlibtest/lib/python3.7/site-packages/pvlib/iotools/__init__.py", line 13, in <module>
    from pvlib.iotools.psm3 import get_psm3  # noqa: F401
  File "/Users/holmgren/miniconda3/envs/pvlibtest/lib/python3.7/site-packages/pvlib/iotools/psm3.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**To Reproduce**
1. `conda create -n pvlibtest python=3.7`
2. `pip install pvlib`
3. `python -c import pvlib`

**Expected behavior**
`pip install pvlib` works from a clean environment.

**Versions:**
 - ``pvlib.__version__``: 0.6.2
 - ``pandas.__version__``: 0.24.2
 - python: 3.7

**Additional context**
#694 added a dependency on requests. The CI environments pull in requests through some of their dependencies, so it wasn't caught there. Should make a new issue for adding CI tests for pip installs into a clean environment.

0.6.3 coming up...

**Comment by mikofski** [comment]
oops! thanks for catching and quick fix!
